// Generated by gencpp from file vision/Ball.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_BALL_H
#define VISION_MESSAGE_BALL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace vision
{
template <class ContainerAllocator>
struct Ball_
{
  typedef Ball_<ContainerAllocator> Type;

  Ball_()
    : header()
    , ball_detected(false)
    , ball_range(0.0)
    , ball_bearing(0.0)
    , ball_radius(0.0)
    , ball_center_x(0)
    , ball_center_y(0)
    , kick_time(0.0)  {
    }
  Ball_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ball_detected(false)
    , ball_range(0.0)
    , ball_bearing(0.0)
    , ball_radius(0.0)
    , ball_center_x(0)
    , ball_center_y(0)
    , kick_time(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _ball_detected_type;
  _ball_detected_type ball_detected;

   typedef double _ball_range_type;
  _ball_range_type ball_range;

   typedef double _ball_bearing_type;
  _ball_bearing_type ball_bearing;

   typedef double _ball_radius_type;
  _ball_radius_type ball_radius;

   typedef int64_t _ball_center_x_type;
  _ball_center_x_type ball_center_x;

   typedef int64_t _ball_center_y_type;
  _ball_center_y_type ball_center_y;

   typedef double _kick_time_type;
  _kick_time_type kick_time;





  typedef boost::shared_ptr< ::vision::Ball_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::Ball_<ContainerAllocator> const> ConstPtr;

}; // struct Ball_

typedef ::vision::Ball_<std::allocator<void> > Ball;

typedef boost::shared_ptr< ::vision::Ball > BallPtr;
typedef boost::shared_ptr< ::vision::Ball const> BallConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::Ball_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::Ball_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'vision': ['/home/lian/robot_ws/src/vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision::Ball_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::Ball_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::Ball_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::Ball_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::Ball_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::Ball_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::Ball_<ContainerAllocator> >
{
  static const char* value()
  {
    return "07dd74c62bc00b3a12c5e1cd0e3a4159";
  }

  static const char* value(const ::vision::Ball_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x07dd74c62bc00b3aULL;
  static const uint64_t static_value2 = 0x12c5e1cd0e3a4159ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::Ball_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/Ball";
  }

  static const char* value(const ::vision::Ball_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::Ball_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool ball_detected\n\
float64 ball_range\n\
float64 ball_bearing\n\
float64 ball_radius\n\
int64 ball_center_x\n\
int64 ball_center_y\n\
float64 kick_time\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::vision::Ball_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::Ball_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ball_detected);
      stream.next(m.ball_range);
      stream.next(m.ball_bearing);
      stream.next(m.ball_radius);
      stream.next(m.ball_center_x);
      stream.next(m.ball_center_y);
      stream.next(m.kick_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ball_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::Ball_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::Ball_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ball_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ball_detected);
    s << indent << "ball_range: ";
    Printer<double>::stream(s, indent + "  ", v.ball_range);
    s << indent << "ball_bearing: ";
    Printer<double>::stream(s, indent + "  ", v.ball_bearing);
    s << indent << "ball_radius: ";
    Printer<double>::stream(s, indent + "  ", v.ball_radius);
    s << indent << "ball_center_x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ball_center_x);
    s << indent << "ball_center_y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ball_center_y);
    s << indent << "kick_time: ";
    Printer<double>::stream(s, indent + "  ", v.kick_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_BALL_H
