// Generated by gencpp from file vision/DepthRequestRequest.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_DEPTHREQUESTREQUEST_H
#define VISION_MESSAGE_DEPTHREQUESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision
{
template <class ContainerAllocator>
struct DepthRequestRequest_
{
  typedef DepthRequestRequest_<ContainerAllocator> Type;

  DepthRequestRequest_()
    : u(0)
    , v(0)  {
    }
  DepthRequestRequest_(const ContainerAllocator& _alloc)
    : u(0)
    , v(0)  {
  (void)_alloc;
    }



   typedef int32_t _u_type;
  _u_type u;

   typedef int32_t _v_type;
  _v_type v;





  typedef boost::shared_ptr< ::vision::DepthRequestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::DepthRequestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DepthRequestRequest_

typedef ::vision::DepthRequestRequest_<std::allocator<void> > DepthRequestRequest;

typedef boost::shared_ptr< ::vision::DepthRequestRequest > DepthRequestRequestPtr;
typedef boost::shared_ptr< ::vision::DepthRequestRequest const> DepthRequestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::DepthRequestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::DepthRequestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'vision': ['/home/lian/robot_ws/src/vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision::DepthRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::DepthRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::DepthRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::DepthRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::DepthRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::DepthRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::DepthRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f06a7e8dd345ffb826d71a489782114b";
  }

  static const char* value(const ::vision::DepthRequestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf06a7e8dd345ffb8ULL;
  static const uint64_t static_value2 = 0x26d71a489782114bULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::DepthRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/DepthRequestRequest";
  }

  static const char* value(const ::vision::DepthRequestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::DepthRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
int32 u\n\
int32 v\n\
";
  }

  static const char* value(const ::vision::DepthRequestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::DepthRequestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.u);
      stream.next(m.v);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DepthRequestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::DepthRequestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::DepthRequestRequest_<ContainerAllocator>& v)
  {
    s << indent << "u: ";
    Printer<int32_t>::stream(s, indent + "  ", v.u);
    s << indent << "v: ";
    Printer<int32_t>::stream(s, indent + "  ", v.v);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_DEPTHREQUESTREQUEST_H
