// Generated by gencpp from file vision/DepthRequest.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_DEPTHREQUEST_H
#define VISION_MESSAGE_DEPTHREQUEST_H

#include <ros/service_traits.h>


#include <vision/DepthRequestRequest.h>
#include <vision/DepthRequestResponse.h>


namespace vision
{

struct DepthRequest
{

typedef DepthRequestRequest Request;
typedef DepthRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DepthRequest
} // namespace vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vision::DepthRequest > {
  static const char* value()
  {
    return "1036fa6d5d2b46f7aa7aaecd35620560";
  }

  static const char* value(const ::vision::DepthRequest&) { return value(); }
};

template<>
struct DataType< ::vision::DepthRequest > {
  static const char* value()
  {
    return "vision/DepthRequest";
  }

  static const char* value(const ::vision::DepthRequest&) { return value(); }
};


// service_traits::MD5Sum< ::vision::DepthRequestRequest> should match 
// service_traits::MD5Sum< ::vision::DepthRequest > 
template<>
struct MD5Sum< ::vision::DepthRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vision::DepthRequest >::value();
  }
  static const char* value(const ::vision::DepthRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision::DepthRequestRequest> should match 
// service_traits::DataType< ::vision::DepthRequest > 
template<>
struct DataType< ::vision::DepthRequestRequest>
{
  static const char* value()
  {
    return DataType< ::vision::DepthRequest >::value();
  }
  static const char* value(const ::vision::DepthRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vision::DepthRequestResponse> should match 
// service_traits::MD5Sum< ::vision::DepthRequest > 
template<>
struct MD5Sum< ::vision::DepthRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vision::DepthRequest >::value();
  }
  static const char* value(const ::vision::DepthRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision::DepthRequestResponse> should match 
// service_traits::DataType< ::vision::DepthRequest > 
template<>
struct DataType< ::vision::DepthRequestResponse>
{
  static const char* value()
  {
    return DataType< ::vision::DepthRequest >::value();
  }
  static const char* value(const ::vision::DepthRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISION_MESSAGE_DEPTHREQUEST_H
