// Generated by gencpp from file vision/DepthRequestResponse.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_DEPTHREQUESTRESPONSE_H
#define VISION_MESSAGE_DEPTHREQUESTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision
{
template <class ContainerAllocator>
struct DepthRequestResponse_
{
  typedef DepthRequestResponse_<ContainerAllocator> Type;

  DepthRequestResponse_()
    : depth(0.0)  {
    }
  DepthRequestResponse_(const ContainerAllocator& _alloc)
    : depth(0.0)  {
  (void)_alloc;
    }



   typedef double _depth_type;
  _depth_type depth;





  typedef boost::shared_ptr< ::vision::DepthRequestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::DepthRequestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DepthRequestResponse_

typedef ::vision::DepthRequestResponse_<std::allocator<void> > DepthRequestResponse;

typedef boost::shared_ptr< ::vision::DepthRequestResponse > DepthRequestResponsePtr;
typedef boost::shared_ptr< ::vision::DepthRequestResponse const> DepthRequestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::DepthRequestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::DepthRequestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'vision': ['/home/lian/robot_ws/src/vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision::DepthRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::DepthRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::DepthRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::DepthRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::DepthRequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::DepthRequestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::DepthRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3493bcd175ed22d87965370b75a0d961";
  }

  static const char* value(const ::vision::DepthRequestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3493bcd175ed22d8ULL;
  static const uint64_t static_value2 = 0x7965370b75a0d961ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::DepthRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/DepthRequestResponse";
  }

  static const char* value(const ::vision::DepthRequestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::DepthRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 depth\n\
\n\
";
  }

  static const char* value(const ::vision::DepthRequestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::DepthRequestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.depth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DepthRequestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::DepthRequestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::DepthRequestResponse_<ContainerAllocator>& v)
  {
    s << indent << "depth: ";
    Printer<double>::stream(s, indent + "  ", v.depth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_DEPTHREQUESTRESPONSE_H
