// Generated by gencpp from file vision/field.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_FIELD_H
#define VISION_MESSAGE_FIELD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision
{
template <class ContainerAllocator>
struct field_
{
  typedef field_<ContainerAllocator> Type;

  field_()
    : width(0)
    , data()  {
    }
  field_(const ContainerAllocator& _alloc)
    : width(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef uint16_t _width_type;
  _width_type width;

   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::vision::field_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::field_<ContainerAllocator> const> ConstPtr;

}; // struct field_

typedef ::vision::field_<std::allocator<void> > field;

typedef boost::shared_ptr< ::vision::field > fieldPtr;
typedef boost::shared_ptr< ::vision::field const> fieldConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::field_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::field_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'vision': ['/home/lian/robot_ws/src/vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision::field_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::field_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::field_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::field_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::field_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::field_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::field_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7238b8238eb8992ed07002d15ada745";
  }

  static const char* value(const ::vision::field_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7238b8238eb8992ULL;
  static const uint64_t static_value2 = 0xed07002d15ada745ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::field_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/field";
  }

  static const char* value(const ::vision::field_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::field_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 width\n\
uint16[] data\n\
";
  }

  static const char* value(const ::vision::field_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::field_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.width);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct field_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::field_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::field_<ContainerAllocator>& v)
  {
    s << indent << "width: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.width);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_FIELD_H
