// Generated by gencpp from file vision/Goalpost.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_GOALPOST_H
#define VISION_MESSAGE_GOALPOST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace vision
{
template <class ContainerAllocator>
struct Goalpost_
{
  typedef Goalpost_<ContainerAllocator> Type;

  Goalpost_()
    : header()
    , goalpost_detected(false)
    , goalpost_number(0)
    , goalpost_left_range(0.0)
    , goalpost_left_bearing(0.0)
    , goalpost_right_range(0.0)
    , goalpost_right_bearing(0.0)
    , goalpost_center_range(0.0)
    , goalpost_center_bearing(0.0)  {
    }
  Goalpost_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goalpost_detected(false)
    , goalpost_number(0)
    , goalpost_left_range(0.0)
    , goalpost_left_bearing(0.0)
    , goalpost_right_range(0.0)
    , goalpost_right_bearing(0.0)
    , goalpost_center_range(0.0)
    , goalpost_center_bearing(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _goalpost_detected_type;
  _goalpost_detected_type goalpost_detected;

   typedef int8_t _goalpost_number_type;
  _goalpost_number_type goalpost_number;

   typedef double _goalpost_left_range_type;
  _goalpost_left_range_type goalpost_left_range;

   typedef double _goalpost_left_bearing_type;
  _goalpost_left_bearing_type goalpost_left_bearing;

   typedef double _goalpost_right_range_type;
  _goalpost_right_range_type goalpost_right_range;

   typedef double _goalpost_right_bearing_type;
  _goalpost_right_bearing_type goalpost_right_bearing;

   typedef double _goalpost_center_range_type;
  _goalpost_center_range_type goalpost_center_range;

   typedef double _goalpost_center_bearing_type;
  _goalpost_center_bearing_type goalpost_center_bearing;





  typedef boost::shared_ptr< ::vision::Goalpost_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::Goalpost_<ContainerAllocator> const> ConstPtr;

}; // struct Goalpost_

typedef ::vision::Goalpost_<std::allocator<void> > Goalpost;

typedef boost::shared_ptr< ::vision::Goalpost > GoalpostPtr;
typedef boost::shared_ptr< ::vision::Goalpost const> GoalpostConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::Goalpost_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::Goalpost_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'vision': ['/home/lian/robot_ws/src/vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision::Goalpost_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::Goalpost_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::Goalpost_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::Goalpost_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::Goalpost_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::Goalpost_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::Goalpost_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7e85911d22877f743fec7cea6c072ce";
  }

  static const char* value(const ::vision::Goalpost_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7e85911d22877f7ULL;
  static const uint64_t static_value2 = 0x43fec7cea6c072ceULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::Goalpost_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/Goalpost";
  }

  static const char* value(const ::vision::Goalpost_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::Goalpost_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool goalpost_detected\n\
int8 goalpost_number   # 3 if only see the middle bar of goalpost. then send out the left and right point as left goalpost and right goalpost\n\
float64 goalpost_left_range\n\
float64 goalpost_left_bearing\n\
float64 goalpost_right_range\n\
float64 goalpost_right_bearing\n\
float64 goalpost_center_range\n\
float64 goalpost_center_bearing\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::vision::Goalpost_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::Goalpost_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goalpost_detected);
      stream.next(m.goalpost_number);
      stream.next(m.goalpost_left_range);
      stream.next(m.goalpost_left_bearing);
      stream.next(m.goalpost_right_range);
      stream.next(m.goalpost_right_bearing);
      stream.next(m.goalpost_center_range);
      stream.next(m.goalpost_center_bearing);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Goalpost_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::Goalpost_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::Goalpost_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goalpost_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.goalpost_detected);
    s << indent << "goalpost_number: ";
    Printer<int8_t>::stream(s, indent + "  ", v.goalpost_number);
    s << indent << "goalpost_left_range: ";
    Printer<double>::stream(s, indent + "  ", v.goalpost_left_range);
    s << indent << "goalpost_left_bearing: ";
    Printer<double>::stream(s, indent + "  ", v.goalpost_left_bearing);
    s << indent << "goalpost_right_range: ";
    Printer<double>::stream(s, indent + "  ", v.goalpost_right_range);
    s << indent << "goalpost_right_bearing: ";
    Printer<double>::stream(s, indent + "  ", v.goalpost_right_bearing);
    s << indent << "goalpost_center_range: ";
    Printer<double>::stream(s, indent + "  ", v.goalpost_center_range);
    s << indent << "goalpost_center_bearing: ";
    Printer<double>::stream(s, indent + "  ", v.goalpost_center_bearing);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_GOALPOST_H
