// Generated by gencpp from file vision/Lines.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_LINES_H
#define VISION_MESSAGE_LINES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace vision
{
template <class ContainerAllocator>
struct Lines_
{
  typedef Lines_<ContainerAllocator> Type;

  Lines_()
    : header()
    , lines_number(0)
    , line_start_x()
    , line_start_y()
    , line_end_x()
    , line_end_y()
    , line_confidence()  {
      line_start_x.assign(0.0);

      line_start_y.assign(0.0);

      line_end_x.assign(0.0);

      line_end_y.assign(0.0);

      line_confidence.assign(0.0);
  }
  Lines_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lines_number(0)
    , line_start_x()
    , line_start_y()
    , line_end_x()
    , line_end_y()
    , line_confidence()  {
  (void)_alloc;
      line_start_x.assign(0.0);

      line_start_y.assign(0.0);

      line_end_x.assign(0.0);

      line_end_y.assign(0.0);

      line_confidence.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _lines_number_type;
  _lines_number_type lines_number;

   typedef boost::array<double, 20>  _line_start_x_type;
  _line_start_x_type line_start_x;

   typedef boost::array<double, 20>  _line_start_y_type;
  _line_start_y_type line_start_y;

   typedef boost::array<double, 20>  _line_end_x_type;
  _line_end_x_type line_end_x;

   typedef boost::array<double, 20>  _line_end_y_type;
  _line_end_y_type line_end_y;

   typedef boost::array<float, 20>  _line_confidence_type;
  _line_confidence_type line_confidence;





  typedef boost::shared_ptr< ::vision::Lines_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::Lines_<ContainerAllocator> const> ConstPtr;

}; // struct Lines_

typedef ::vision::Lines_<std::allocator<void> > Lines;

typedef boost::shared_ptr< ::vision::Lines > LinesPtr;
typedef boost::shared_ptr< ::vision::Lines const> LinesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::Lines_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::Lines_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'vision': ['/home/lian/robot_ws/src/vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision::Lines_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::Lines_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::Lines_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::Lines_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::Lines_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::Lines_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::Lines_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26fb3619336498992b94003d734b3dd9";
  }

  static const char* value(const ::vision::Lines_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26fb361933649899ULL;
  static const uint64_t static_value2 = 0x2b94003d734b3dd9ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::Lines_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/Lines";
  }

  static const char* value(const ::vision::Lines_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::Lines_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint8 lines_number  \n\
float64[20] line_start_x                 \n\
float64[20] line_start_y \n\
float64[20] line_end_x                 \n\
float64[20] line_end_y               \n\
float32[20] line_confidence               # confidence 0..1\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::vision::Lines_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::Lines_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lines_number);
      stream.next(m.line_start_x);
      stream.next(m.line_start_y);
      stream.next(m.line_end_x);
      stream.next(m.line_end_y);
      stream.next(m.line_confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Lines_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::Lines_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::Lines_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lines_number: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lines_number);
    s << indent << "line_start_x[]" << std::endl;
    for (size_t i = 0; i < v.line_start_x.size(); ++i)
    {
      s << indent << "  line_start_x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.line_start_x[i]);
    }
    s << indent << "line_start_y[]" << std::endl;
    for (size_t i = 0; i < v.line_start_y.size(); ++i)
    {
      s << indent << "  line_start_y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.line_start_y[i]);
    }
    s << indent << "line_end_x[]" << std::endl;
    for (size_t i = 0; i < v.line_end_x.size(); ++i)
    {
      s << indent << "  line_end_x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.line_end_x[i]);
    }
    s << indent << "line_end_y[]" << std::endl;
    for (size_t i = 0; i < v.line_end_y.size(); ++i)
    {
      s << indent << "  line_end_y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.line_end_y[i]);
    }
    s << indent << "line_confidence[]" << std::endl;
    for (size_t i = 0; i < v.line_confidence.size(); ++i)
    {
      s << indent << "  line_confidence[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.line_confidence[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_LINES_H
