// Generated by gencpp from file vision/Markers.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_MARKERS_H
#define VISION_MESSAGE_MARKERS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace vision
{
template <class ContainerAllocator>
struct Markers_
{
  typedef Markers_<ContainerAllocator> Type;

  Markers_()
    : header()
    , markers_detected(false)
    , markers_number(0)
    , marker_id()
    , marker_rotvec_x()
    , marker_rotvec_y()
    , marker_rotvec_z()
    , marker_transvec_x()
    , marker_transvec_y()
    , marker_transvec_z()  {
    }
  Markers_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , markers_detected(false)
    , markers_number(0)
    , marker_id(_alloc)
    , marker_rotvec_x(_alloc)
    , marker_rotvec_y(_alloc)
    , marker_rotvec_z(_alloc)
    , marker_transvec_x(_alloc)
    , marker_transvec_y(_alloc)
    , marker_transvec_z(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _markers_detected_type;
  _markers_detected_type markers_detected;

   typedef uint16_t _markers_number_type;
  _markers_number_type markers_number;

   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _marker_id_type;
  _marker_id_type marker_id;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _marker_rotvec_x_type;
  _marker_rotvec_x_type marker_rotvec_x;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _marker_rotvec_y_type;
  _marker_rotvec_y_type marker_rotvec_y;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _marker_rotvec_z_type;
  _marker_rotvec_z_type marker_rotvec_z;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _marker_transvec_x_type;
  _marker_transvec_x_type marker_transvec_x;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _marker_transvec_y_type;
  _marker_transvec_y_type marker_transvec_y;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _marker_transvec_z_type;
  _marker_transvec_z_type marker_transvec_z;





  typedef boost::shared_ptr< ::vision::Markers_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::Markers_<ContainerAllocator> const> ConstPtr;

}; // struct Markers_

typedef ::vision::Markers_<std::allocator<void> > Markers;

typedef boost::shared_ptr< ::vision::Markers > MarkersPtr;
typedef boost::shared_ptr< ::vision::Markers const> MarkersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::Markers_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::Markers_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'vision': ['/home/lian/robot_ws/src/vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision::Markers_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::Markers_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::Markers_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::Markers_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::Markers_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::Markers_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::Markers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a85c45b00f3e0388fd3fe5a952433ae";
  }

  static const char* value(const ::vision::Markers_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a85c45b00f3e038ULL;
  static const uint64_t static_value2 = 0x8fd3fe5a952433aeULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::Markers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/Markers";
  }

  static const char* value(const ::vision::Markers_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::Markers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool markers_detected\n\
uint16 markers_number  #all together, if more than two seen, placed from closer two to further\n\
int8[] marker_id\n\
float64[] marker_rotvec_x\n\
float64[] marker_rotvec_y\n\
float64[] marker_rotvec_z\n\
float64[] marker_transvec_x\n\
float64[] marker_transvec_y\n\
float64[] marker_transvec_z\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::vision::Markers_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::Markers_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.markers_detected);
      stream.next(m.markers_number);
      stream.next(m.marker_id);
      stream.next(m.marker_rotvec_x);
      stream.next(m.marker_rotvec_y);
      stream.next(m.marker_rotvec_z);
      stream.next(m.marker_transvec_x);
      stream.next(m.marker_transvec_y);
      stream.next(m.marker_transvec_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Markers_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::Markers_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::Markers_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "markers_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.markers_detected);
    s << indent << "markers_number: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.markers_number);
    s << indent << "marker_id[]" << std::endl;
    for (size_t i = 0; i < v.marker_id.size(); ++i)
    {
      s << indent << "  marker_id[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.marker_id[i]);
    }
    s << indent << "marker_rotvec_x[]" << std::endl;
    for (size_t i = 0; i < v.marker_rotvec_x.size(); ++i)
    {
      s << indent << "  marker_rotvec_x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.marker_rotvec_x[i]);
    }
    s << indent << "marker_rotvec_y[]" << std::endl;
    for (size_t i = 0; i < v.marker_rotvec_y.size(); ++i)
    {
      s << indent << "  marker_rotvec_y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.marker_rotvec_y[i]);
    }
    s << indent << "marker_rotvec_z[]" << std::endl;
    for (size_t i = 0; i < v.marker_rotvec_z.size(); ++i)
    {
      s << indent << "  marker_rotvec_z[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.marker_rotvec_z[i]);
    }
    s << indent << "marker_transvec_x[]" << std::endl;
    for (size_t i = 0; i < v.marker_transvec_x.size(); ++i)
    {
      s << indent << "  marker_transvec_x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.marker_transvec_x[i]);
    }
    s << indent << "marker_transvec_y[]" << std::endl;
    for (size_t i = 0; i < v.marker_transvec_y.size(); ++i)
    {
      s << indent << "  marker_transvec_y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.marker_transvec_y[i]);
    }
    s << indent << "marker_transvec_z[]" << std::endl;
    for (size_t i = 0; i < v.marker_transvec_z.size(); ++i)
    {
      s << indent << "  marker_transvec_z[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.marker_transvec_z[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_MARKERS_H
