// Generated by gencpp from file vision/ObjectOnImage.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_OBJECTONIMAGE_H
#define VISION_MESSAGE_OBJECTONIMAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision
{
template <class ContainerAllocator>
struct ObjectOnImage_
{
  typedef ObjectOnImage_<ContainerAllocator> Type;

  ObjectOnImage_()
    : object_type(0)
    , u()
    , v()  {
    }
  ObjectOnImage_(const ContainerAllocator& _alloc)
    : object_type(0)
    , u(_alloc)
    , v(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _object_type_type;
  _object_type_type object_type;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _u_type;
  _u_type u;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _v_type;
  _v_type v;





  typedef boost::shared_ptr< ::vision::ObjectOnImage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::ObjectOnImage_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectOnImage_

typedef ::vision::ObjectOnImage_<std::allocator<void> > ObjectOnImage;

typedef boost::shared_ptr< ::vision::ObjectOnImage > ObjectOnImagePtr;
typedef boost::shared_ptr< ::vision::ObjectOnImage const> ObjectOnImageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::ObjectOnImage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::ObjectOnImage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'vision': ['/home/lian/robot_ws/src/vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision::ObjectOnImage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::ObjectOnImage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::ObjectOnImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::ObjectOnImage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::ObjectOnImage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::ObjectOnImage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::ObjectOnImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8b2eee0990ad6385c56c5984bb6dea1";
  }

  static const char* value(const ::vision::ObjectOnImage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8b2eee0990ad638ULL;
  static const uint64_t static_value2 = 0x5c56c5984bb6dea1ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::ObjectOnImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/ObjectOnImage";
  }

  static const char* value(const ::vision::ObjectOnImage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::ObjectOnImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 object_type\n\
uint8[] u\n\
uint8[] v\n\
";
  }

  static const char* value(const ::vision::ObjectOnImage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::ObjectOnImage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_type);
      stream.next(m.u);
      stream.next(m.v);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectOnImage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::ObjectOnImage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::ObjectOnImage_<ContainerAllocator>& v)
  {
    s << indent << "object_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.object_type);
    s << indent << "u[]" << std::endl;
    for (size_t i = 0; i < v.u.size(); ++i)
    {
      s << indent << "  u[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.u[i]);
    }
    s << indent << "v[]" << std::endl;
    for (size_t i = 0; i < v.v.size(); ++i)
    {
      s << indent << "  v[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.v[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_OBJECTONIMAGE_H
