// Generated by gencpp from file vision/Opponents.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_OPPONENTS_H
#define VISION_MESSAGE_OPPONENTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace vision
{
template <class ContainerAllocator>
struct Opponents_
{
  typedef Opponents_<ContainerAllocator> Type;

  Opponents_()
    : header()
    , opponent_detected(false)
    , opponent_number(0)
    , opponent_range()
    , opponent_bearing()  {
      opponent_range.assign(0.0);

      opponent_bearing.assign(0.0);
  }
  Opponents_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , opponent_detected(false)
    , opponent_number(0)
    , opponent_range()
    , opponent_bearing()  {
  (void)_alloc;
      opponent_range.assign(0.0);

      opponent_bearing.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _opponent_detected_type;
  _opponent_detected_type opponent_detected;

   typedef uint8_t _opponent_number_type;
  _opponent_number_type opponent_number;

   typedef boost::array<double, 5>  _opponent_range_type;
  _opponent_range_type opponent_range;

   typedef boost::array<double, 5>  _opponent_bearing_type;
  _opponent_bearing_type opponent_bearing;





  typedef boost::shared_ptr< ::vision::Opponents_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::Opponents_<ContainerAllocator> const> ConstPtr;

}; // struct Opponents_

typedef ::vision::Opponents_<std::allocator<void> > Opponents;

typedef boost::shared_ptr< ::vision::Opponents > OpponentsPtr;
typedef boost::shared_ptr< ::vision::Opponents const> OpponentsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::Opponents_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::Opponents_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'vision': ['/home/lian/robot_ws/src/vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision::Opponents_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::Opponents_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::Opponents_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::Opponents_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::Opponents_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::Opponents_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::Opponents_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef41a5e204617f0c2b713c70ec7cf155";
  }

  static const char* value(const ::vision::Opponents_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef41a5e204617f0cULL;
  static const uint64_t static_value2 = 0x2b713c70ec7cf155ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::Opponents_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/Opponents";
  }

  static const char* value(const ::vision::Opponents_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::Opponents_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool opponent_detected\n\
uint8 opponent_number\n\
float64[5] opponent_range\n\
float64[5] opponent_bearing\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::vision::Opponents_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::Opponents_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.opponent_detected);
      stream.next(m.opponent_number);
      stream.next(m.opponent_range);
      stream.next(m.opponent_bearing);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Opponents_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::Opponents_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::Opponents_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "opponent_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.opponent_detected);
    s << indent << "opponent_number: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.opponent_number);
    s << indent << "opponent_range[]" << std::endl;
    for (size_t i = 0; i < v.opponent_range.size(); ++i)
    {
      s << indent << "  opponent_range[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.opponent_range[i]);
    }
    s << indent << "opponent_bearing[]" << std::endl;
    for (size_t i = 0; i < v.opponent_bearing.size(); ++i)
    {
      s << indent << "  opponent_bearing[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.opponent_bearing[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_OPPONENTS_H
