# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from localization/OutputData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class OutputData(genpy.Message):
  _md5sum = "0d5bb91e3132d7eb05a2ae36456b86d6"
  _type = "localization/OutputData"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header 				# for time stamp
geometry_msgs/Pose2D robotPose        		# Pose of the robot according to the particle filter localization
geometry_msgs/Pose2D robotHeadPose              # Pose of the robot head according to the particle filter localization
float32 robotPoseConfidence               	# confidence 0..1 for the robot_pose
bool bBallWasSeen                               # boolean variable for ball detection
geometry_msgs/Point ballCenterInImage		# coordinates of ball center in the image
float32 ballDistance				# ball distance from robot as seen in the image
float32 ballAngle				# ball angle from center as seen in the image, [-90,90]
geometry_msgs/Point ballCenterOnField		# coordinates of ball center on field relative to robot localization
bool bOpponentWasSeen                           # boolean variable for opponent detection
geometry_msgs/Point opponentLeftEndInImage	# coordinates of opponent left end point in the image
geometry_msgs/Point opponentRightEndInImage	# coordinates of opponent right end point in the image
float32 opponentDistance			# opponent distance from robot as seen in the image
float32 opponentAngle				# opponent angle from center as seen in the image, [-90,90]
geometry_msgs/Point opponentCenterOnField	# coordinates of opponent center on field relative to robot localization
float32 opponentRadiusOnField			# estimated radius of opponent on field
bool bObstacleWasSeen                           # boolean variable for obstacle detection
int32 iObstacleNumber                           # index of obstacle
geometry_msgs/Point[5] obstacleLeftEndInImage	# coordinates of obstacle left end point in the image
geometry_msgs/Point[5] obstacleRightEndInImage	# coordinates of obstacle right end point in the image
float32[5] obstacleDistance                     # obstacle distance from robot as seen in the image
float32[5] obstacleAngle			# obstacle angle from center as seen in the image, [-90,90]
geometry_msgs/Point[5] obstacleCenterOnField	# coordinates of obstacle center on field relative to robot localization
float32[5] obstacleRadiusOnField		# estimated radius of obstacle on field


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose2D
# Deprecated
# Please use the full 3D pose.

# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.

# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.


# This expresses a position and orientation on a 2D manifold.

float64 x
float64 y
float64 theta

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['header','robotPose','robotHeadPose','robotPoseConfidence','bBallWasSeen','ballCenterInImage','ballDistance','ballAngle','ballCenterOnField','bOpponentWasSeen','opponentLeftEndInImage','opponentRightEndInImage','opponentDistance','opponentAngle','opponentCenterOnField','opponentRadiusOnField','bObstacleWasSeen','iObstacleNumber','obstacleLeftEndInImage','obstacleRightEndInImage','obstacleDistance','obstacleAngle','obstacleCenterOnField','obstacleRadiusOnField']
  _slot_types = ['std_msgs/Header','geometry_msgs/Pose2D','geometry_msgs/Pose2D','float32','bool','geometry_msgs/Point','float32','float32','geometry_msgs/Point','bool','geometry_msgs/Point','geometry_msgs/Point','float32','float32','geometry_msgs/Point','float32','bool','int32','geometry_msgs/Point[5]','geometry_msgs/Point[5]','float32[5]','float32[5]','geometry_msgs/Point[5]','float32[5]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,robotPose,robotHeadPose,robotPoseConfidence,bBallWasSeen,ballCenterInImage,ballDistance,ballAngle,ballCenterOnField,bOpponentWasSeen,opponentLeftEndInImage,opponentRightEndInImage,opponentDistance,opponentAngle,opponentCenterOnField,opponentRadiusOnField,bObstacleWasSeen,iObstacleNumber,obstacleLeftEndInImage,obstacleRightEndInImage,obstacleDistance,obstacleAngle,obstacleCenterOnField,obstacleRadiusOnField

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OutputData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.robotPose is None:
        self.robotPose = geometry_msgs.msg.Pose2D()
      if self.robotHeadPose is None:
        self.robotHeadPose = geometry_msgs.msg.Pose2D()
      if self.robotPoseConfidence is None:
        self.robotPoseConfidence = 0.
      if self.bBallWasSeen is None:
        self.bBallWasSeen = False
      if self.ballCenterInImage is None:
        self.ballCenterInImage = geometry_msgs.msg.Point()
      if self.ballDistance is None:
        self.ballDistance = 0.
      if self.ballAngle is None:
        self.ballAngle = 0.
      if self.ballCenterOnField is None:
        self.ballCenterOnField = geometry_msgs.msg.Point()
      if self.bOpponentWasSeen is None:
        self.bOpponentWasSeen = False
      if self.opponentLeftEndInImage is None:
        self.opponentLeftEndInImage = geometry_msgs.msg.Point()
      if self.opponentRightEndInImage is None:
        self.opponentRightEndInImage = geometry_msgs.msg.Point()
      if self.opponentDistance is None:
        self.opponentDistance = 0.
      if self.opponentAngle is None:
        self.opponentAngle = 0.
      if self.opponentCenterOnField is None:
        self.opponentCenterOnField = geometry_msgs.msg.Point()
      if self.opponentRadiusOnField is None:
        self.opponentRadiusOnField = 0.
      if self.bObstacleWasSeen is None:
        self.bObstacleWasSeen = False
      if self.iObstacleNumber is None:
        self.iObstacleNumber = 0
      if self.obstacleLeftEndInImage is None:
        self.obstacleLeftEndInImage = [geometry_msgs.msg.Point() for _ in range(5)]
      if self.obstacleRightEndInImage is None:
        self.obstacleRightEndInImage = [geometry_msgs.msg.Point() for _ in range(5)]
      if self.obstacleDistance is None:
        self.obstacleDistance = [0.] * 5
      if self.obstacleAngle is None:
        self.obstacleAngle = [0.] * 5
      if self.obstacleCenterOnField is None:
        self.obstacleCenterOnField = [geometry_msgs.msg.Point() for _ in range(5)]
      if self.obstacleRadiusOnField is None:
        self.obstacleRadiusOnField = [0.] * 5
    else:
      self.header = std_msgs.msg.Header()
      self.robotPose = geometry_msgs.msg.Pose2D()
      self.robotHeadPose = geometry_msgs.msg.Pose2D()
      self.robotPoseConfidence = 0.
      self.bBallWasSeen = False
      self.ballCenterInImage = geometry_msgs.msg.Point()
      self.ballDistance = 0.
      self.ballAngle = 0.
      self.ballCenterOnField = geometry_msgs.msg.Point()
      self.bOpponentWasSeen = False
      self.opponentLeftEndInImage = geometry_msgs.msg.Point()
      self.opponentRightEndInImage = geometry_msgs.msg.Point()
      self.opponentDistance = 0.
      self.opponentAngle = 0.
      self.opponentCenterOnField = geometry_msgs.msg.Point()
      self.opponentRadiusOnField = 0.
      self.bObstacleWasSeen = False
      self.iObstacleNumber = 0
      self.obstacleLeftEndInImage = [geometry_msgs.msg.Point() for _ in range(5)]
      self.obstacleRightEndInImage = [geometry_msgs.msg.Point() for _ in range(5)]
      self.obstacleDistance = [0.] * 5
      self.obstacleAngle = [0.] * 5
      self.obstacleCenterOnField = [geometry_msgs.msg.Point() for _ in range(5)]
      self.obstacleRadiusOnField = [0.] * 5

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6dfB3d2f3dB6d2f3dfBi().pack(_x.robotPose.x, _x.robotPose.y, _x.robotPose.theta, _x.robotHeadPose.x, _x.robotHeadPose.y, _x.robotHeadPose.theta, _x.robotPoseConfidence, _x.bBallWasSeen, _x.ballCenterInImage.x, _x.ballCenterInImage.y, _x.ballCenterInImage.z, _x.ballDistance, _x.ballAngle, _x.ballCenterOnField.x, _x.ballCenterOnField.y, _x.ballCenterOnField.z, _x.bOpponentWasSeen, _x.opponentLeftEndInImage.x, _x.opponentLeftEndInImage.y, _x.opponentLeftEndInImage.z, _x.opponentRightEndInImage.x, _x.opponentRightEndInImage.y, _x.opponentRightEndInImage.z, _x.opponentDistance, _x.opponentAngle, _x.opponentCenterOnField.x, _x.opponentCenterOnField.y, _x.opponentCenterOnField.z, _x.opponentRadiusOnField, _x.bObstacleWasSeen, _x.iObstacleNumber))
      for val1 in self.obstacleLeftEndInImage:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      for val1 in self.obstacleRightEndInImage:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      buff.write(_get_struct_5f().pack(*self.obstacleDistance))
      buff.write(_get_struct_5f().pack(*self.obstacleAngle))
      for val1 in self.obstacleCenterOnField:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      buff.write(_get_struct_5f().pack(*self.obstacleRadiusOnField))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.robotPose is None:
        self.robotPose = geometry_msgs.msg.Pose2D()
      if self.robotHeadPose is None:
        self.robotHeadPose = geometry_msgs.msg.Pose2D()
      if self.ballCenterInImage is None:
        self.ballCenterInImage = geometry_msgs.msg.Point()
      if self.ballCenterOnField is None:
        self.ballCenterOnField = geometry_msgs.msg.Point()
      if self.opponentLeftEndInImage is None:
        self.opponentLeftEndInImage = geometry_msgs.msg.Point()
      if self.opponentRightEndInImage is None:
        self.opponentRightEndInImage = geometry_msgs.msg.Point()
      if self.opponentCenterOnField is None:
        self.opponentCenterOnField = geometry_msgs.msg.Point()
      if self.obstacleLeftEndInImage is None:
        self.obstacleLeftEndInImage = None
      if self.obstacleRightEndInImage is None:
        self.obstacleRightEndInImage = None
      if self.obstacleCenterOnField is None:
        self.obstacleCenterOnField = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 199
      (_x.robotPose.x, _x.robotPose.y, _x.robotPose.theta, _x.robotHeadPose.x, _x.robotHeadPose.y, _x.robotHeadPose.theta, _x.robotPoseConfidence, _x.bBallWasSeen, _x.ballCenterInImage.x, _x.ballCenterInImage.y, _x.ballCenterInImage.z, _x.ballDistance, _x.ballAngle, _x.ballCenterOnField.x, _x.ballCenterOnField.y, _x.ballCenterOnField.z, _x.bOpponentWasSeen, _x.opponentLeftEndInImage.x, _x.opponentLeftEndInImage.y, _x.opponentLeftEndInImage.z, _x.opponentRightEndInImage.x, _x.opponentRightEndInImage.y, _x.opponentRightEndInImage.z, _x.opponentDistance, _x.opponentAngle, _x.opponentCenterOnField.x, _x.opponentCenterOnField.y, _x.opponentCenterOnField.z, _x.opponentRadiusOnField, _x.bObstacleWasSeen, _x.iObstacleNumber,) = _get_struct_6dfB3d2f3dB6d2f3dfBi().unpack(str[start:end])
      self.bBallWasSeen = bool(self.bBallWasSeen)
      self.bOpponentWasSeen = bool(self.bOpponentWasSeen)
      self.bObstacleWasSeen = bool(self.bObstacleWasSeen)
      self.obstacleLeftEndInImage = []
      for i in range(0, 5):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.obstacleLeftEndInImage.append(val1)
      self.obstacleRightEndInImage = []
      for i in range(0, 5):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.obstacleRightEndInImage.append(val1)
      start = end
      end += 20
      self.obstacleDistance = _get_struct_5f().unpack(str[start:end])
      start = end
      end += 20
      self.obstacleAngle = _get_struct_5f().unpack(str[start:end])
      self.obstacleCenterOnField = []
      for i in range(0, 5):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.obstacleCenterOnField.append(val1)
      start = end
      end += 20
      self.obstacleRadiusOnField = _get_struct_5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6dfB3d2f3dB6d2f3dfBi().pack(_x.robotPose.x, _x.robotPose.y, _x.robotPose.theta, _x.robotHeadPose.x, _x.robotHeadPose.y, _x.robotHeadPose.theta, _x.robotPoseConfidence, _x.bBallWasSeen, _x.ballCenterInImage.x, _x.ballCenterInImage.y, _x.ballCenterInImage.z, _x.ballDistance, _x.ballAngle, _x.ballCenterOnField.x, _x.ballCenterOnField.y, _x.ballCenterOnField.z, _x.bOpponentWasSeen, _x.opponentLeftEndInImage.x, _x.opponentLeftEndInImage.y, _x.opponentLeftEndInImage.z, _x.opponentRightEndInImage.x, _x.opponentRightEndInImage.y, _x.opponentRightEndInImage.z, _x.opponentDistance, _x.opponentAngle, _x.opponentCenterOnField.x, _x.opponentCenterOnField.y, _x.opponentCenterOnField.z, _x.opponentRadiusOnField, _x.bObstacleWasSeen, _x.iObstacleNumber))
      for val1 in self.obstacleLeftEndInImage:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      for val1 in self.obstacleRightEndInImage:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      buff.write(self.obstacleDistance.tostring())
      buff.write(self.obstacleAngle.tostring())
      for val1 in self.obstacleCenterOnField:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      buff.write(self.obstacleRadiusOnField.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.robotPose is None:
        self.robotPose = geometry_msgs.msg.Pose2D()
      if self.robotHeadPose is None:
        self.robotHeadPose = geometry_msgs.msg.Pose2D()
      if self.ballCenterInImage is None:
        self.ballCenterInImage = geometry_msgs.msg.Point()
      if self.ballCenterOnField is None:
        self.ballCenterOnField = geometry_msgs.msg.Point()
      if self.opponentLeftEndInImage is None:
        self.opponentLeftEndInImage = geometry_msgs.msg.Point()
      if self.opponentRightEndInImage is None:
        self.opponentRightEndInImage = geometry_msgs.msg.Point()
      if self.opponentCenterOnField is None:
        self.opponentCenterOnField = geometry_msgs.msg.Point()
      if self.obstacleLeftEndInImage is None:
        self.obstacleLeftEndInImage = None
      if self.obstacleRightEndInImage is None:
        self.obstacleRightEndInImage = None
      if self.obstacleCenterOnField is None:
        self.obstacleCenterOnField = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 199
      (_x.robotPose.x, _x.robotPose.y, _x.robotPose.theta, _x.robotHeadPose.x, _x.robotHeadPose.y, _x.robotHeadPose.theta, _x.robotPoseConfidence, _x.bBallWasSeen, _x.ballCenterInImage.x, _x.ballCenterInImage.y, _x.ballCenterInImage.z, _x.ballDistance, _x.ballAngle, _x.ballCenterOnField.x, _x.ballCenterOnField.y, _x.ballCenterOnField.z, _x.bOpponentWasSeen, _x.opponentLeftEndInImage.x, _x.opponentLeftEndInImage.y, _x.opponentLeftEndInImage.z, _x.opponentRightEndInImage.x, _x.opponentRightEndInImage.y, _x.opponentRightEndInImage.z, _x.opponentDistance, _x.opponentAngle, _x.opponentCenterOnField.x, _x.opponentCenterOnField.y, _x.opponentCenterOnField.z, _x.opponentRadiusOnField, _x.bObstacleWasSeen, _x.iObstacleNumber,) = _get_struct_6dfB3d2f3dB6d2f3dfBi().unpack(str[start:end])
      self.bBallWasSeen = bool(self.bBallWasSeen)
      self.bOpponentWasSeen = bool(self.bOpponentWasSeen)
      self.bObstacleWasSeen = bool(self.bObstacleWasSeen)
      self.obstacleLeftEndInImage = []
      for i in range(0, 5):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.obstacleLeftEndInImage.append(val1)
      self.obstacleRightEndInImage = []
      for i in range(0, 5):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.obstacleRightEndInImage.append(val1)
      start = end
      end += 20
      self.obstacleDistance = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=5)
      start = end
      end += 20
      self.obstacleAngle = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=5)
      self.obstacleCenterOnField = []
      for i in range(0, 5):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.obstacleCenterOnField.append(val1)
      start = end
      end += 20
      self.obstacleRadiusOnField = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=5)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6dfB3d2f3dB6d2f3dfBi = None
def _get_struct_6dfB3d2f3dB6d2f3dfBi():
    global _struct_6dfB3d2f3dB6d2f3dfBi
    if _struct_6dfB3d2f3dB6d2f3dfBi is None:
        _struct_6dfB3d2f3dB6d2f3dfBi = struct.Struct("<6dfB3d2f3dB6d2f3dfBi")
    return _struct_6dfB3d2f3dB6d2f3dfBi
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_5f = None
def _get_struct_5f():
    global _struct_5f
    if _struct_5f is None:
        _struct_5f = struct.Struct("<5f")
    return _struct_5f
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
