(cl:defpackage localization-msg
  (:use )
  (:export
   "<GOALPOSTSDETECTED>"
   "GOALPOSTSDETECTED"
   "<LINESDETECTED>"
   "LINESDETECTED"
   "<MEANPOSECONFSTAMPED>"
   "MEANPOSECONFSTAMPED"
   "<OBJECTSDETECTED>"
   "OBJECTSDETECTED"
   "<OBSTACLESDETECTED>"
   "OBSTACLESDETECTED"
   "<OUTPUTDATA>"
   "OUTPUTDATA"
   "<PARTICLE>"
   "PARTICLE"
   "<PARTICLESET>"
   "PARTICLESET"
   "<WORLDOBJECTS>"
   "WORLDOBJECTS"
  ))

