// Generated by gencpp from file decision/gyro_euler.msg
// DO NOT EDIT!


#ifndef DECISION_MESSAGE_GYRO_EULER_H
#define DECISION_MESSAGE_GYRO_EULER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace decision
{
template <class ContainerAllocator>
struct gyro_euler_
{
  typedef gyro_euler_<ContainerAllocator> Type;

  gyro_euler_()
    : euler_angle()  {
    }
  gyro_euler_(const ContainerAllocator& _alloc)
    : euler_angle(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _euler_angle_type;
  _euler_angle_type euler_angle;





  typedef boost::shared_ptr< ::decision::gyro_euler_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::decision::gyro_euler_<ContainerAllocator> const> ConstPtr;

}; // struct gyro_euler_

typedef ::decision::gyro_euler_<std::allocator<void> > gyro_euler;

typedef boost::shared_ptr< ::decision::gyro_euler > gyro_eulerPtr;
typedef boost::shared_ptr< ::decision::gyro_euler const> gyro_eulerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::decision::gyro_euler_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::decision::gyro_euler_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace decision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'decision': ['/home/lian/robot_ws/src/decision/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::decision::gyro_euler_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::decision::gyro_euler_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision::gyro_euler_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision::gyro_euler_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision::gyro_euler_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision::gyro_euler_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::decision::gyro_euler_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0ed725f607be591af507cbf7836e5ed";
  }

  static const char* value(const ::decision::gyro_euler_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0ed725f607be591ULL;
  static const uint64_t static_value2 = 0xaf507cbf7836e5edULL;
};

template<class ContainerAllocator>
struct DataType< ::decision::gyro_euler_<ContainerAllocator> >
{
  static const char* value()
  {
    return "decision/gyro_euler";
  }

  static const char* value(const ::decision::gyro_euler_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::decision::gyro_euler_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3 euler_angle\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::decision::gyro_euler_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::decision::gyro_euler_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.euler_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gyro_euler_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::decision::gyro_euler_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::decision::gyro_euler_<ContainerAllocator>& v)
  {
    s << indent << "euler_angle: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.euler_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DECISION_MESSAGE_GYRO_EULER_H
