// Generated by gencpp from file decision/head_angle.msg
// DO NOT EDIT!


#ifndef DECISION_MESSAGE_HEAD_ANGLE_H
#define DECISION_MESSAGE_HEAD_ANGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace decision
{
template <class ContainerAllocator>
struct head_angle_
{
  typedef head_angle_<ContainerAllocator> Type;

  head_angle_()
    : angle_head_pitch(0.0)
    , angle_head_yaw(0.0)  {
    }
  head_angle_(const ContainerAllocator& _alloc)
    : angle_head_pitch(0.0)
    , angle_head_yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _angle_head_pitch_type;
  _angle_head_pitch_type angle_head_pitch;

   typedef double _angle_head_yaw_type;
  _angle_head_yaw_type angle_head_yaw;





  typedef boost::shared_ptr< ::decision::head_angle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::decision::head_angle_<ContainerAllocator> const> ConstPtr;

}; // struct head_angle_

typedef ::decision::head_angle_<std::allocator<void> > head_angle;

typedef boost::shared_ptr< ::decision::head_angle > head_anglePtr;
typedef boost::shared_ptr< ::decision::head_angle const> head_angleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::decision::head_angle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::decision::head_angle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace decision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'decision': ['/home/lian/robot_ws/src/decision/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::decision::head_angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::decision::head_angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision::head_angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision::head_angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision::head_angle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision::head_angle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::decision::head_angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13464c771052649b3693335e0dc785b9";
  }

  static const char* value(const ::decision::head_angle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13464c771052649bULL;
  static const uint64_t static_value2 = 0x3693335e0dc785b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::decision::head_angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "decision/head_angle";
  }

  static const char* value(const ::decision::head_angle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::decision::head_angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 angle_head_pitch	#pitch\n\
float64 angle_head_yaw  	#yaw\n\
";
  }

  static const char* value(const ::decision::head_angle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::decision::head_angle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle_head_pitch);
      stream.next(m.angle_head_yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct head_angle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::decision::head_angle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::decision::head_angle_<ContainerAllocator>& v)
  {
    s << indent << "angle_head_pitch: ";
    Printer<double>::stream(s, indent + "  ", v.angle_head_pitch);
    s << indent << "angle_head_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.angle_head_yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DECISION_MESSAGE_HEAD_ANGLE_H
