// Generated by gencpp from file decision/OutputData.msg
// DO NOT EDIT!


#ifndef DECISION_MESSAGE_OUTPUTDATA_H
#define DECISION_MESSAGE_OUTPUTDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace decision
{
template <class ContainerAllocator>
struct OutputData_
{
  typedef OutputData_<ContainerAllocator> Type;

  OutputData_()
    : header()
    , robotPose()
    , robotPoseConfidence(0.0)
    , bBallWasSeen(false)
    , ballCenterInImage()
    , ballDistance(0.0)
    , ballAngle(0.0)
    , ballCenterOnField()
    , bObstacleWasSeen(false)
    , iObstacleNumber(0)
    , obstacleLeftEndInImage()
    , obstacleRightEndInImage()
    , obstacleDistance()
    , obstacleAngle()
    , obstacleCenterOnField()
    , obstacleRadiusOnField()
    , bKeeperWasSeen(false)
    , keeperLeftStartOnField()
    , keeperRightEndOnField()  {
    }
  OutputData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robotPose(_alloc)
    , robotPoseConfidence(0.0)
    , bBallWasSeen(false)
    , ballCenterInImage(_alloc)
    , ballDistance(0.0)
    , ballAngle(0.0)
    , ballCenterOnField(_alloc)
    , bObstacleWasSeen(false)
    , iObstacleNumber(0)
    , obstacleLeftEndInImage(_alloc)
    , obstacleRightEndInImage(_alloc)
    , obstacleDistance(_alloc)
    , obstacleAngle(_alloc)
    , obstacleCenterOnField(_alloc)
    , obstacleRadiusOnField(_alloc)
    , bKeeperWasSeen(false)
    , keeperLeftStartOnField(_alloc)
    , keeperRightEndOnField(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _robotPose_type;
  _robotPose_type robotPose;

   typedef float _robotPoseConfidence_type;
  _robotPoseConfidence_type robotPoseConfidence;

   typedef uint8_t _bBallWasSeen_type;
  _bBallWasSeen_type bBallWasSeen;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _ballCenterInImage_type;
  _ballCenterInImage_type ballCenterInImage;

   typedef float _ballDistance_type;
  _ballDistance_type ballDistance;

   typedef float _ballAngle_type;
  _ballAngle_type ballAngle;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _ballCenterOnField_type;
  _ballCenterOnField_type ballCenterOnField;

   typedef uint8_t _bObstacleWasSeen_type;
  _bObstacleWasSeen_type bObstacleWasSeen;

   typedef int32_t _iObstacleNumber_type;
  _iObstacleNumber_type iObstacleNumber;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _obstacleLeftEndInImage_type;
  _obstacleLeftEndInImage_type obstacleLeftEndInImage;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _obstacleRightEndInImage_type;
  _obstacleRightEndInImage_type obstacleRightEndInImage;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _obstacleDistance_type;
  _obstacleDistance_type obstacleDistance;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _obstacleAngle_type;
  _obstacleAngle_type obstacleAngle;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _obstacleCenterOnField_type;
  _obstacleCenterOnField_type obstacleCenterOnField;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _obstacleRadiusOnField_type;
  _obstacleRadiusOnField_type obstacleRadiusOnField;

   typedef uint8_t _bKeeperWasSeen_type;
  _bKeeperWasSeen_type bKeeperWasSeen;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _keeperLeftStartOnField_type;
  _keeperLeftStartOnField_type keeperLeftStartOnField;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _keeperRightEndOnField_type;
  _keeperRightEndOnField_type keeperRightEndOnField;





  typedef boost::shared_ptr< ::decision::OutputData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::decision::OutputData_<ContainerAllocator> const> ConstPtr;

}; // struct OutputData_

typedef ::decision::OutputData_<std::allocator<void> > OutputData;

typedef boost::shared_ptr< ::decision::OutputData > OutputDataPtr;
typedef boost::shared_ptr< ::decision::OutputData const> OutputDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::decision::OutputData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::decision::OutputData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace decision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'decision': ['/home/lian/robot_ws/src/decision/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::decision::OutputData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::decision::OutputData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision::OutputData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision::OutputData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision::OutputData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision::OutputData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::decision::OutputData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd064faf37c8b9975f133c15e75ac7aa";
  }

  static const char* value(const ::decision::OutputData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd064faf37c8b997ULL;
  static const uint64_t static_value2 = 0x5f133c15e75ac7aaULL;
};

template<class ContainerAllocator>
struct DataType< ::decision::OutputData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "decision/OutputData";
  }

  static const char* value(const ::decision::OutputData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::decision::OutputData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#	data published by the localization node.\n\
\n\
std_msgs/Header header 								# for time stamp\n\
geometry_msgs/Pose2D robotPose        				# Pose of the robot according to the particle filter localization	\n\
float32 robotPoseConfidence               			# confidence 0..1 for the robot_pose\n\
bool bBallWasSeen                               	# boolean variable for ball detection\n\
geometry_msgs/Point ballCenterInImage				# coordinates of ball center in the image\n\
float32 ballDistance								# ball distance from robot as seen in the image\n\
float32 ballAngle									# ball angle from center as seen in the image, [-90,90]\n\
geometry_msgs/Point ballCenterOnField				# coordinates of ball center on field relative to robot localization	\n\
bool bObstacleWasSeen                           	# boolean variable for obstacle detection\n\
int32 iObstacleNumber                           	# index of obstacle, if 2 found this is 2\n\
geometry_msgs/Point[] obstacleLeftEndInImage		# coordinates of obstacle left end point in the image\n\
geometry_msgs/Point[] obstacleRightEndInImage		# coordinates of obstacle right end point in the image\n\
float32[] obstacleDistance							# obstacle distance from robot as seen in the image\n\
float32[] obstacleAngle								# obstacle angle from center as seen in the image, [-90,90]\n\
geometry_msgs/Point[] obstacleCenterOnField			# coordinates of obstacle center on field relative to robot localization	\n\
float32[] obstacleRadiusOnField						# estimated radius of obstacle on field\n\
bool bKeeperWasSeen                             	# boolean variable for goalkeeper detection\n\
geometry_msgs/Point keeperLeftStartOnField      	# coordinates of goalkeeper left leg start point on field\n\
geometry_msgs/Point keeperRightEndOnField       	# coordinates of goalkeeper right leg end point on field\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# Deprecated\n\
# Please use the full 3D pose.\n\
\n\
# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n\
\n\
# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n\
\n\
\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::decision::OutputData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::decision::OutputData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robotPose);
      stream.next(m.robotPoseConfidence);
      stream.next(m.bBallWasSeen);
      stream.next(m.ballCenterInImage);
      stream.next(m.ballDistance);
      stream.next(m.ballAngle);
      stream.next(m.ballCenterOnField);
      stream.next(m.bObstacleWasSeen);
      stream.next(m.iObstacleNumber);
      stream.next(m.obstacleLeftEndInImage);
      stream.next(m.obstacleRightEndInImage);
      stream.next(m.obstacleDistance);
      stream.next(m.obstacleAngle);
      stream.next(m.obstacleCenterOnField);
      stream.next(m.obstacleRadiusOnField);
      stream.next(m.bKeeperWasSeen);
      stream.next(m.keeperLeftStartOnField);
      stream.next(m.keeperRightEndOnField);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OutputData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::decision::OutputData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::decision::OutputData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robotPose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.robotPose);
    s << indent << "robotPoseConfidence: ";
    Printer<float>::stream(s, indent + "  ", v.robotPoseConfidence);
    s << indent << "bBallWasSeen: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bBallWasSeen);
    s << indent << "ballCenterInImage: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.ballCenterInImage);
    s << indent << "ballDistance: ";
    Printer<float>::stream(s, indent + "  ", v.ballDistance);
    s << indent << "ballAngle: ";
    Printer<float>::stream(s, indent + "  ", v.ballAngle);
    s << indent << "ballCenterOnField: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.ballCenterOnField);
    s << indent << "bObstacleWasSeen: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bObstacleWasSeen);
    s << indent << "iObstacleNumber: ";
    Printer<int32_t>::stream(s, indent + "  ", v.iObstacleNumber);
    s << indent << "obstacleLeftEndInImage[]" << std::endl;
    for (size_t i = 0; i < v.obstacleLeftEndInImage.size(); ++i)
    {
      s << indent << "  obstacleLeftEndInImage[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacleLeftEndInImage[i]);
    }
    s << indent << "obstacleRightEndInImage[]" << std::endl;
    for (size_t i = 0; i < v.obstacleRightEndInImage.size(); ++i)
    {
      s << indent << "  obstacleRightEndInImage[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacleRightEndInImage[i]);
    }
    s << indent << "obstacleDistance[]" << std::endl;
    for (size_t i = 0; i < v.obstacleDistance.size(); ++i)
    {
      s << indent << "  obstacleDistance[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.obstacleDistance[i]);
    }
    s << indent << "obstacleAngle[]" << std::endl;
    for (size_t i = 0; i < v.obstacleAngle.size(); ++i)
    {
      s << indent << "  obstacleAngle[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.obstacleAngle[i]);
    }
    s << indent << "obstacleCenterOnField[]" << std::endl;
    for (size_t i = 0; i < v.obstacleCenterOnField.size(); ++i)
    {
      s << indent << "  obstacleCenterOnField[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacleCenterOnField[i]);
    }
    s << indent << "obstacleRadiusOnField[]" << std::endl;
    for (size_t i = 0; i < v.obstacleRadiusOnField.size(); ++i)
    {
      s << indent << "  obstacleRadiusOnField[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.obstacleRadiusOnField[i]);
    }
    s << indent << "bKeeperWasSeen: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bKeeperWasSeen);
    s << indent << "keeperLeftStartOnField: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.keeperLeftStartOnField);
    s << indent << "keeperRightEndOnField: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.keeperRightEndOnField);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DECISION_MESSAGE_OUTPUTDATA_H
