// Generated by gencpp from file decision/Pathplaning_theRequest.msg
// DO NOT EDIT!


#ifndef DECISION_MESSAGE_PATHPLANING_THEREQUEST_H
#define DECISION_MESSAGE_PATHPLANING_THEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace decision
{
template <class ContainerAllocator>
struct Pathplaning_theRequest_
{
  typedef Pathplaning_theRequest_<ContainerAllocator> Type;

  Pathplaning_theRequest_()
    : state(false)  {
    }
  Pathplaning_theRequest_(const ContainerAllocator& _alloc)
    : state(false)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::decision::Pathplaning_theRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::decision::Pathplaning_theRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Pathplaning_theRequest_

typedef ::decision::Pathplaning_theRequest_<std::allocator<void> > Pathplaning_theRequest;

typedef boost::shared_ptr< ::decision::Pathplaning_theRequest > Pathplaning_theRequestPtr;
typedef boost::shared_ptr< ::decision::Pathplaning_theRequest const> Pathplaning_theRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::decision::Pathplaning_theRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::decision::Pathplaning_theRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace decision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'decision': ['/home/lian/robot_ws/src/decision/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::decision::Pathplaning_theRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::decision::Pathplaning_theRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision::Pathplaning_theRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision::Pathplaning_theRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision::Pathplaning_theRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision::Pathplaning_theRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::decision::Pathplaning_theRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "001fde3cab9e313a150416ff09c08ee4";
  }

  static const char* value(const ::decision::Pathplaning_theRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x001fde3cab9e313aULL;
  static const uint64_t static_value2 = 0x150416ff09c08ee4ULL;
};

template<class ContainerAllocator>
struct DataType< ::decision::Pathplaning_theRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "decision/Pathplaning_theRequest";
  }

  static const char* value(const ::decision::Pathplaning_theRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::decision::Pathplaning_theRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool state\n\
";
  }

  static const char* value(const ::decision::Pathplaning_theRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::decision::Pathplaning_theRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pathplaning_theRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::decision::Pathplaning_theRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::decision::Pathplaning_theRequest_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DECISION_MESSAGE_PATHPLANING_THEREQUEST_H
