// Generated by gencpp from file decision/Pathplaning_theResponse.msg
// DO NOT EDIT!


#ifndef DECISION_MESSAGE_PATHPLANING_THERESPONSE_H
#define DECISION_MESSAGE_PATHPLANING_THERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace decision
{
template <class ContainerAllocator>
struct Pathplaning_theResponse_
{
  typedef Pathplaning_theResponse_<ContainerAllocator> Type;

  Pathplaning_theResponse_()
    : theta_result(0.0)  {
    }
  Pathplaning_theResponse_(const ContainerAllocator& _alloc)
    : theta_result(0.0)  {
  (void)_alloc;
    }



   typedef float _theta_result_type;
  _theta_result_type theta_result;





  typedef boost::shared_ptr< ::decision::Pathplaning_theResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::decision::Pathplaning_theResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Pathplaning_theResponse_

typedef ::decision::Pathplaning_theResponse_<std::allocator<void> > Pathplaning_theResponse;

typedef boost::shared_ptr< ::decision::Pathplaning_theResponse > Pathplaning_theResponsePtr;
typedef boost::shared_ptr< ::decision::Pathplaning_theResponse const> Pathplaning_theResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::decision::Pathplaning_theResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::decision::Pathplaning_theResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace decision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'decision': ['/home/lian/robot_ws/src/decision/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::decision::Pathplaning_theResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::decision::Pathplaning_theResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision::Pathplaning_theResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision::Pathplaning_theResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision::Pathplaning_theResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision::Pathplaning_theResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::decision::Pathplaning_theResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "38f246c33d90c8333d784465d938cba6";
  }

  static const char* value(const ::decision::Pathplaning_theResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x38f246c33d90c833ULL;
  static const uint64_t static_value2 = 0x3d784465d938cba6ULL;
};

template<class ContainerAllocator>
struct DataType< ::decision::Pathplaning_theResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "decision/Pathplaning_theResponse";
  }

  static const char* value(const ::decision::Pathplaning_theResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::decision::Pathplaning_theResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 theta_result\n\
\n\
";
  }

  static const char* value(const ::decision::Pathplaning_theResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::decision::Pathplaning_theResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.theta_result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pathplaning_theResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::decision::Pathplaning_theResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::decision::Pathplaning_theResponse_<ContainerAllocator>& v)
  {
    s << indent << "theta_result: ";
    Printer<float>::stream(s, indent + "  ", v.theta_result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DECISION_MESSAGE_PATHPLANING_THERESPONSE_H
