// Generated by gencpp from file decision/UDPReceived.msg
// DO NOT EDIT!


#ifndef DECISION_MESSAGE_UDPRECEIVED_H
#define DECISION_MESSAGE_UDPRECEIVED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace decision
{
template <class ContainerAllocator>
struct UDPReceived_
{
  typedef UDPReceived_<ContainerAllocator> Type;

  UDPReceived_()
    : header()
    , received_data()  {
      received_data.assign(0.0);
  }
  UDPReceived_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , received_data()  {
  (void)_alloc;
      received_data.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 10>  _received_data_type;
  _received_data_type received_data;





  typedef boost::shared_ptr< ::decision::UDPReceived_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::decision::UDPReceived_<ContainerAllocator> const> ConstPtr;

}; // struct UDPReceived_

typedef ::decision::UDPReceived_<std::allocator<void> > UDPReceived;

typedef boost::shared_ptr< ::decision::UDPReceived > UDPReceivedPtr;
typedef boost::shared_ptr< ::decision::UDPReceived const> UDPReceivedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::decision::UDPReceived_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::decision::UDPReceived_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace decision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'decision': ['/home/lian/robot_ws/src/decision/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::decision::UDPReceived_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::decision::UDPReceived_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision::UDPReceived_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision::UDPReceived_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision::UDPReceived_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision::UDPReceived_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::decision::UDPReceived_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6946b75416098a1dfb2a52c2eb0f84b3";
  }

  static const char* value(const ::decision::UDPReceived_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6946b75416098a1dULL;
  static const uint64_t static_value2 = 0xfb2a52c2eb0f84b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::decision::UDPReceived_<ContainerAllocator> >
{
  static const char* value()
  {
    return "decision/UDPReceived";
  }

  static const char* value(const ::decision::UDPReceived_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::decision::UDPReceived_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
float32[10] received_data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::decision::UDPReceived_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::decision::UDPReceived_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.received_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UDPReceived_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::decision::UDPReceived_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::decision::UDPReceived_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "received_data[]" << std::endl;
    for (size_t i = 0; i < v.received_data.size(); ++i)
    {
      s << indent << "  received_data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.received_data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DECISION_MESSAGE_UDPRECEIVED_H
