// Generated by gencpp from file decision/walkResponse.msg
// DO NOT EDIT!


#ifndef DECISION_MESSAGE_WALKRESPONSE_H
#define DECISION_MESSAGE_WALKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace decision
{
template <class ContainerAllocator>
struct walkResponse_
{
  typedef walkResponse_<ContainerAllocator> Type;

  walkResponse_()
    : results(0)  {
    }
  walkResponse_(const ContainerAllocator& _alloc)
    : results(0)  {
  (void)_alloc;
    }



   typedef int32_t _results_type;
  _results_type results;





  typedef boost::shared_ptr< ::decision::walkResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::decision::walkResponse_<ContainerAllocator> const> ConstPtr;

}; // struct walkResponse_

typedef ::decision::walkResponse_<std::allocator<void> > walkResponse;

typedef boost::shared_ptr< ::decision::walkResponse > walkResponsePtr;
typedef boost::shared_ptr< ::decision::walkResponse const> walkResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::decision::walkResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::decision::walkResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace decision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'decision': ['/home/lian/robot_ws/src/decision/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::decision::walkResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::decision::walkResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision::walkResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision::walkResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision::walkResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision::walkResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::decision::walkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "197ce17ed92dd2e138792386b1f2fbad";
  }

  static const char* value(const ::decision::walkResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x197ce17ed92dd2e1ULL;
  static const uint64_t static_value2 = 0x38792386b1f2fbadULL;
};

template<class ContainerAllocator>
struct DataType< ::decision::walkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "decision/walkResponse";
  }

  static const char* value(const ::decision::walkResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::decision::walkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 results\n\
\n\
";
  }

  static const char* value(const ::decision::walkResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::decision::walkResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.results);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct walkResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::decision::walkResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::decision::walkResponse_<ContainerAllocator>& v)
  {
    s << indent << "results: ";
    Printer<int32_t>::stream(s, indent + "  ", v.results);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DECISION_MESSAGE_WALKRESPONSE_H
