(cl:in-package vision-msg)
(cl:export '(HEADER-VAL
          HEADER
          GOALPOST_DETECTED-VAL
          GOALPOST_DETECTED
          GOALPOST_NUMBER-VAL
          GOALPOST_NUMBER
          GOALPOST_LEFT_RANGE-VAL
          GOALPOST_LEFT_RANGE
          GOALPOST_LEFT_BEARING-VAL
          GOALPOST_LEFT_BEARING
          GOALPOST_RIGHT_RANGE-VAL
          GOALPOST_RIGHT_RANGE
          GOALPOST_RIGHT_BEARING-VAL
          GOALPOST_RIGHT_BEARING
          GOALPOST_CENTER_RANGE-VAL
          GOALPOST_CENTER_RANGE
          GOALPOST_CENTER_BEARING-VAL
          GOALPOST_CENTER_BEARING
))