(cl:in-package vision-msg)
(cl:export '(BOBSTACLEWASSEEN-VAL
          BOBSTACLEWASSEEN
          ILEFTEDGEINIMAGEX-VAL
          ILEFTEDGEINIMAGEX
          ILEFTEDGEINIMAGEY-VAL
          ILEFTEDGEINIMAGEY
          IRIGHTEDGEINIMAGEX-VAL
          IRIGHTEDGEINIMAGEX
          IRIGHTEDGEINIMAGEY-VAL
          IRIGHTEDGEINIMAGEY
          IHEIGHTINIMAGE-VAL
          IHEIGHTINIMAGE
          INUMBER-VAL
          INUMBER
          IOTHERSLEFTEDGEINIMAGEX-VAL
          IOTHERSLEFTEDGEINIMAGEX
          IOTHERSRIGHTEDGEINIMAGEX-VAL
          IOTHERSRIGHTEDGEINIMAGEX
          IOTHERSINIMAGEY-VAL
          IOTHERSINIMAGEY
          IOTHERSHEIGHTINIMAGE-VAL
          IOTHERSHEIGHTINIMAGE
))