// Generated by gencpp from file localization/WorldObjects.msg
// DO NOT EDIT!


#ifndef LOCALIZATION_MESSAGE_WORLDOBJECTS_H
#define LOCALIZATION_MESSAGE_WORLDOBJECTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <localization/ObjectsDetected.h>
#include <localization/GoalpostsDetected.h>
#include <localization/LinesDetected.h>
#include <localization/ObstaclesDetected.h>

namespace localization
{
template <class ContainerAllocator>
struct WorldObjects_
{
  typedef WorldObjects_<ContainerAllocator> Type;

  WorldObjects_()
    : header()
    , objects()
    , goalposts()
    , lines()
    , obstacles()  {
    }
  WorldObjects_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)
    , goalposts(_alloc)
    , lines(_alloc)
    , obstacles(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::localization::ObjectsDetected_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::localization::ObjectsDetected_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;

   typedef std::vector< ::localization::GoalpostsDetected_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::localization::GoalpostsDetected_<ContainerAllocator> >::other >  _goalposts_type;
  _goalposts_type goalposts;

   typedef std::vector< ::localization::LinesDetected_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::localization::LinesDetected_<ContainerAllocator> >::other >  _lines_type;
  _lines_type lines;

   typedef std::vector< ::localization::ObstaclesDetected_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::localization::ObstaclesDetected_<ContainerAllocator> >::other >  _obstacles_type;
  _obstacles_type obstacles;





  typedef boost::shared_ptr< ::localization::WorldObjects_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::localization::WorldObjects_<ContainerAllocator> const> ConstPtr;

}; // struct WorldObjects_

typedef ::localization::WorldObjects_<std::allocator<void> > WorldObjects;

typedef boost::shared_ptr< ::localization::WorldObjects > WorldObjectsPtr;
typedef boost::shared_ptr< ::localization::WorldObjects const> WorldObjectsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::localization::WorldObjects_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::localization::WorldObjects_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace localization

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'tf': ['/opt/ros/kinetic/share/tf/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'localization': ['/home/lian/robot_ws/src/localization/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::localization::WorldObjects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localization::WorldObjects_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localization::WorldObjects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localization::WorldObjects_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization::WorldObjects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization::WorldObjects_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::localization::WorldObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3b402e0a736a3c111358cf72848e29c";
  }

  static const char* value(const ::localization::WorldObjects_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3b402e0a736a3c1ULL;
  static const uint64_t static_value2 = 0x11358cf72848e29cULL;
};

template<class ContainerAllocator>
struct DataType< ::localization::WorldObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "localization/WorldObjects";
  }

  static const char* value(const ::localization::WorldObjects_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::localization::WorldObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
#add more for the lines and such, like in detections\n\
ObjectsDetected[] objects\n\
GoalpostsDetected[] goalposts\n\
LinesDetected[] lines\n\
ObstaclesDetected[] obstacles\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: localization/ObjectsDetected\n\
geometry_msgs/Pose2D pose        # Pose\n\
uint8 type                       # Type (see field_model::WorldObject::Type)\n\
float32 confidence               # confidence 0..1\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# Deprecated\n\
# Please use the full 3D pose.\n\
\n\
# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n\
\n\
# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n\
\n\
\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
\n\
================================================================================\n\
MSG: localization/GoalpostsDetected\n\
geometry_msgs/Pose2D pose        # Pose\n\
uint8 type                       # Type (see field_model::WorldObject::Type)\n\
float32 confidence               # confidence 0..1\n\
\n\
================================================================================\n\
MSG: localization/LinesDetected\n\
float32 x1\n\
float32 y1\n\
float32 x2\n\
float32 y2\n\
\n\
================================================================================\n\
MSG: localization/ObstaclesDetected\n\
geometry_msgs/Pose2D pose        # Pose\n\
uint8 type                       # Type 0 for opponent, 1 for other obstacle\n\
float32 confidence               # confidence 0..1\n\
";
  }

  static const char* value(const ::localization::WorldObjects_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::localization::WorldObjects_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
      stream.next(m.goalposts);
      stream.next(m.lines);
      stream.next(m.obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WorldObjects_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::localization::WorldObjects_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::localization::WorldObjects_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::localization::ObjectsDetected_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
    s << indent << "goalposts[]" << std::endl;
    for (size_t i = 0; i < v.goalposts.size(); ++i)
    {
      s << indent << "  goalposts[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::localization::GoalpostsDetected_<ContainerAllocator> >::stream(s, indent + "    ", v.goalposts[i]);
    }
    s << indent << "lines[]" << std::endl;
    for (size_t i = 0; i < v.lines.size(); ++i)
    {
      s << indent << "  lines[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::localization::LinesDetected_<ContainerAllocator> >::stream(s, indent + "    ", v.lines[i]);
    }
    s << indent << "obstacles[]" << std::endl;
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      s << indent << "  obstacles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::localization::ObstaclesDetected_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCALIZATION_MESSAGE_WORLDOBJECTS_H
