// Generated by gencpp from file head_motion/head_control.msg
// DO NOT EDIT!


#ifndef HEAD_MOTION_MESSAGE_HEAD_CONTROL_H
#define HEAD_MOTION_MESSAGE_HEAD_CONTROL_H

#include <ros/service_traits.h>


#include <head_motion/head_controlRequest.h>
#include <head_motion/head_controlResponse.h>


namespace head_motion
{

struct head_control
{

typedef head_controlRequest Request;
typedef head_controlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct head_control
} // namespace head_motion


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::head_motion::head_control > {
  static const char* value()
  {
    return "e4aff7be97fd6298f4a9b30300ac7316";
  }

  static const char* value(const ::head_motion::head_control&) { return value(); }
};

template<>
struct DataType< ::head_motion::head_control > {
  static const char* value()
  {
    return "head_motion/head_control";
  }

  static const char* value(const ::head_motion::head_control&) { return value(); }
};


// service_traits::MD5Sum< ::head_motion::head_controlRequest> should match 
// service_traits::MD5Sum< ::head_motion::head_control > 
template<>
struct MD5Sum< ::head_motion::head_controlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::head_motion::head_control >::value();
  }
  static const char* value(const ::head_motion::head_controlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::head_motion::head_controlRequest> should match 
// service_traits::DataType< ::head_motion::head_control > 
template<>
struct DataType< ::head_motion::head_controlRequest>
{
  static const char* value()
  {
    return DataType< ::head_motion::head_control >::value();
  }
  static const char* value(const ::head_motion::head_controlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::head_motion::head_controlResponse> should match 
// service_traits::MD5Sum< ::head_motion::head_control > 
template<>
struct MD5Sum< ::head_motion::head_controlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::head_motion::head_control >::value();
  }
  static const char* value(const ::head_motion::head_controlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::head_motion::head_controlResponse> should match 
// service_traits::DataType< ::head_motion::head_control > 
template<>
struct DataType< ::head_motion::head_controlResponse>
{
  static const char* value()
  {
    return DataType< ::head_motion::head_control >::value();
  }
  static const char* value(const ::head_motion::head_controlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HEAD_MOTION_MESSAGE_HEAD_CONTROL_H
