// Generated by gencpp from file head_motion/head_pose.msg
// DO NOT EDIT!


#ifndef HEAD_MOTION_MESSAGE_HEAD_POSE_H
#define HEAD_MOTION_MESSAGE_HEAD_POSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace head_motion
{
template <class ContainerAllocator>
struct head_pose_
{
  typedef head_pose_<ContainerAllocator> Type;

  head_pose_()
    : yaw(0)
    , pitch(0)  {
    }
  head_pose_(const ContainerAllocator& _alloc)
    : yaw(0)
    , pitch(0)  {
  (void)_alloc;
    }



   typedef int64_t _yaw_type;
  _yaw_type yaw;

   typedef int64_t _pitch_type;
  _pitch_type pitch;





  typedef boost::shared_ptr< ::head_motion::head_pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::head_motion::head_pose_<ContainerAllocator> const> ConstPtr;

}; // struct head_pose_

typedef ::head_motion::head_pose_<std::allocator<void> > head_pose;

typedef boost::shared_ptr< ::head_motion::head_pose > head_posePtr;
typedef boost::shared_ptr< ::head_motion::head_pose const> head_poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::head_motion::head_pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::head_motion::head_pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace head_motion

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'head_motion': ['/home/lian/robot_ws/src/head_motion/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::head_motion::head_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::head_motion::head_pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::head_motion::head_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::head_motion::head_pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::head_motion::head_pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::head_motion::head_pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::head_motion::head_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a639ba30f63c6c2e9b511b1c6df08e3a";
  }

  static const char* value(const ::head_motion::head_pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa639ba30f63c6c2eULL;
  static const uint64_t static_value2 = 0x9b511b1c6df08e3aULL;
};

template<class ContainerAllocator>
struct DataType< ::head_motion::head_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "head_motion/head_pose";
  }

  static const char* value(const ::head_motion::head_pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::head_motion::head_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 yaw\n\
int64 pitch\n\
";
  }

  static const char* value(const ::head_motion::head_pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::head_motion::head_pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.yaw);
      stream.next(m.pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct head_pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::head_motion::head_pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::head_motion::head_pose_<ContainerAllocator>& v)
  {
    s << indent << "yaw: ";
    Printer<int64_t>::stream(s, indent + "  ", v.yaw);
    s << indent << "pitch: ";
    Printer<int64_t>::stream(s, indent + "  ", v.pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEAD_MOTION_MESSAGE_HEAD_POSE_H
