// Generated by gencpp from file head_motion/head_controlRequest.msg
// DO NOT EDIT!


#ifndef HEAD_MOTION_MESSAGE_HEAD_CONTROLREQUEST_H
#define HEAD_MOTION_MESSAGE_HEAD_CONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace head_motion
{
template <class ContainerAllocator>
struct head_controlRequest_
{
  typedef head_controlRequest_<ContainerAllocator> Type;

  head_controlRequest_()
    : pitch(0.0)
    , yaw(0.0)
    , PID(0)  {
    }
  head_controlRequest_(const ContainerAllocator& _alloc)
    : pitch(0.0)
    , yaw(0.0)
    , PID(0)  {
  (void)_alloc;
    }



   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef int32_t _PID_type;
  _PID_type PID;





  typedef boost::shared_ptr< ::head_motion::head_controlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::head_motion::head_controlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct head_controlRequest_

typedef ::head_motion::head_controlRequest_<std::allocator<void> > head_controlRequest;

typedef boost::shared_ptr< ::head_motion::head_controlRequest > head_controlRequestPtr;
typedef boost::shared_ptr< ::head_motion::head_controlRequest const> head_controlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::head_motion::head_controlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::head_motion::head_controlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace head_motion

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'head_motion': ['/home/lian/robot_ws/src/head_motion/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::head_motion::head_controlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::head_motion::head_controlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::head_motion::head_controlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::head_motion::head_controlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::head_motion::head_controlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::head_motion::head_controlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::head_motion::head_controlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed99a51039733c1c24be21a8c023a83d";
  }

  static const char* value(const ::head_motion::head_controlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed99a51039733c1cULL;
  static const uint64_t static_value2 = 0x24be21a8c023a83dULL;
};

template<class ContainerAllocator>
struct DataType< ::head_motion::head_controlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "head_motion/head_controlRequest";
  }

  static const char* value(const ::head_motion::head_controlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::head_motion::head_controlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 pitch\n\
float64 yaw\n\
int32 PID\n\
";
  }

  static const char* value(const ::head_motion::head_controlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::head_motion::head_controlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.PID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct head_controlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::head_motion::head_controlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::head_motion::head_controlRequest_<ContainerAllocator>& v)
  {
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "PID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.PID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEAD_MOTION_MESSAGE_HEAD_CONTROLREQUEST_H
