(cl:in-package decision-msg)
(cl:export '(BOBSTACLEWASSEEN-VAL
          BOBSTACLEWASSEEN
          IOBSTACLENUMBER-VAL
          IOBSTACLENUMBER
          ILEFTEDGEINIMAGEX-VAL
          ILEFTEDGEINIMAGEX
          ILEFTEDGEINIMAGEY-VAL
          ILEFTEDGEINIMAGEY
          IRIGHTEDGEINIMAGEX-VAL
          IRIGHTEDGEINIMAGEX
          IRIGHTEDGEINIMAGEY-VAL
          IRIGHTEDGEINIMAGEY
          IHEIGHTINIMAGE-VAL
          IHEIGHTINIMAGE
          FDISTANCE-VAL
          FDISTANCE
          FANGLE-VAL
          FANGLE
))